#项目端口,名称等信息
server:
  port: 8000
  servlet:
    application-display-name: secKill
#数据库配置
spring:
  profiles:
    active: dev
  datasource:
    druid:
      filters: stat,wall,logback
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000 #1秒慢查询
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1 FROM DUAL
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
  redis:
    jedis:
      pool:
        max-active: 4
        max-idle: 8
        max-wait: 100
        min-idle: 2
#redis
#mybatis配置
mybatis:
  mapper-locations: mapper
#pagehelper配置
pagehelper:
  dialect: mysql
  reasonable: true
  row-bounds-with-count: true
  offset-as-page-num: true
#zookeeper配置
zk:
  address: localhost:2181