#项目端口,名称等信息
server:
  port: 8000
  servlet:
    application-display-name: secKill

#数据库配置
spring:
  profiles:
    active: wx
  datasource:
    druid:
      filters: stat,wall,logback
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000 #1秒慢查询
      test-on-borrow: false
      test-on-return: false
      validation-query: SELECT 1 FROM DUAL
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      test-while-idle: true

#mybatis配置
mybatis:
  mapper-locations: mapper