spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/flashSale?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
      username: root
      password: root

#redis配置
  redis:
    url:
    password: